"use client";

import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";
import { saveAs } from "file-saver";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica" },
  header: { marginBottom: 20 },
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 4 },
  subtitle: { fontSize: 12, color: "#666", marginBottom: 16 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 12, fontWeight: "bold", marginBottom: 8, borderBottomWidth: 1, borderBottomColor: "#ddd", paddingBottom: 4 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  label: { color: "#666" },
  value: { fontWeight: "bold" },
  tableHeader: { flexDirection: "row", backgroundColor: "#f3f4f6", padding: 6, fontWeight: "bold" },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#eee", padding: 6 },
  col1: { width: "40%" },
  col2: { width: "15%" },
  col3: { width: "15%" },
  col4: { width: "15%" },
  col5: { width: "15%" },
  totalRow: { flexDirection: "row", justifyContent: "flex-end", marginTop: 8, paddingTop: 8, borderTopWidth: 2, borderTopColor: "#333" },
  totalLabel: { fontSize: 12, fontWeight: "bold", marginRight: 16 },
  totalValue: { fontSize: 12, fontWeight: "bold" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", color: "#999", fontSize: 8 },
});

interface POPDFData {
  poNumber: string;
  description?: string | null;
  status: string;
  totalAmount: string;
  currency: string;
  createdAt: string;
  vendor: { name: string; email: string };
  department: { name: string };
  requester: { name: string };
  lineItems: {
    description: string;
    quantity: string;
    unitPrice: string;
    totalPrice: string;
  }[];
}

function PODocument({ data }: { data: POPDFData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Purchase Order</Text>
          <Text style={styles.subtitle}>{data.poNumber}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Details</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Status:</Text>
            <Text style={styles.value}>{data.status}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date:</Text>
            <Text style={styles.value}>{data.createdAt}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Vendor:</Text>
            <Text style={styles.value}>{data.vendor.name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Department:</Text>
            <Text style={styles.value}>{data.department.name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Requester:</Text>
            <Text style={styles.value}>{data.requester.name}</Text>
          </View>
          {data.description && (
            <View style={styles.row}>
              <Text style={styles.label}>Description:</Text>
              <Text style={styles.value}>{data.description}</Text>
            </View>
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Line Items</Text>
          <View style={styles.tableHeader}>
            <Text style={styles.col1}>Description</Text>
            <Text style={styles.col2}>Qty</Text>
            <Text style={styles.col3}>Unit Price</Text>
            <Text style={styles.col4}>Total</Text>
          </View>
          {data.lineItems.map((item, index) => (
            <View key={index} style={styles.tableRow}>
              <Text style={styles.col1}>{item.description}</Text>
              <Text style={styles.col2}>{item.quantity}</Text>
              <Text style={styles.col3}>{data.currency} {item.unitPrice}</Text>
              <Text style={styles.col4}>{data.currency} {item.totalPrice}</Text>
            </View>
          ))}
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Total:</Text>
            <Text style={styles.totalValue}>{data.currency} {data.totalAmount}</Text>
          </View>
        </View>

        <Text style={styles.footer}>
          Generated by KSafe Financial Budget Management System
        </Text>
      </Page>
    </Document>
  );
}

export async function generatePOPDF(data: POPDFData) {
  const blob = await pdf(<PODocument data={data} />).toBlob();
  saveAs(blob, `${data.poNumber}.pdf`);
}
